# fly.toml app configuration file generated for wedding-ecosystem-api on 2026-07-10T09:29:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wedding-ecosystem-api"
primary_region = "cgk" # Jakarta, Indonesia (Ultra-low latency)

[build]
  builder = "nixpacks"

[build.args]
  NIXPACKS_BUILD_CMD = "npm ci && npx prisma generate --schema=packages/db/prisma/schema.prisma && npx turbo build --filter=@wedding/api..."

[env]
  PORT = "4000"
  NODE_ENV = "production"

[processes]
  app = 'node packages/api/dist/index.js'

[[services]]
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 250
    soft_limit = 200
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = "10s"
    grace_period = "15s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "2s"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '512mb'
  memory_mb = 512
  processes = ['app']
  size = 'shared-cpu-1x'
